### ISSUE TITLE
脚本报错呀~error from callback 

### ISSUE THREAD

**Issue by jicki** [knva/wsmud-game#1]
# error  logs
```
error from callback <bound method wsgamePlayer.on_open of <wsgamePlayer.wsgamePlayer object at 0x7efcdf178cf8>>: on_open() missing 1 required positional argument: 'ws'
  File "/usr/local/lib/python3.6/site-packages/websocket/_app.py", line 343, in _callback
    callback(*args)
```
同一个账户下有多个 角色 的时候~如何选择？

另外:
    什么时候~增加其他功能~~

    练功~~  刷副本~~~

**Comment by knva** [comment]
本项目已停止维护
你可以访问下面这个链接试试刷副本
[``](https://greasyfork.org/zh-CN/scripts/371372-wsmud-pluginss)[](https://greasyfork.org/zh-CN/scripts/375851-wsmud-raid)
